import { execFileSync } from 'node:child_process';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const repositoryRoot = resolve(appRoot, '../..');
const configRoot = join(repositoryRoot, 'configs');
const outputPath = join(appRoot, 'lib/generated/seed-configs.ts');

const names = (await readdir(configRoot))
  .filter((name) => name.endsWith('.json'))
  .sort((left, right) => left.localeCompare(right));

if (names.length === 0) {
  throw new Error(`Не найдены JSON-конфиги в ${configRoot}`);
}

const entries = [];
for (const fileName of names) {
  const configName = fileName.slice(0, -'.json'.length);
  const raw = await readFile(join(configRoot, fileName), 'utf8');
  entries.push(`  ${JSON.stringify(configName)}: ${JSON.stringify(raw)},`);
}

const gitSha = execFileSync('git', ['rev-parse', 'HEAD'], {
  cwd: repositoryRoot,
  encoding: 'utf8',
}).trim();

const source = `// Generated by scripts/generate-seed.mjs. Do not edit by hand.\n` +
  `export const seedConfigText = {\n${entries.join('\n')}\n} as const;\n\n` +
  `export const seedGitSha = ${JSON.stringify(gitSha)};\n` +
  `export type SeedConfigName = keyof typeof seedConfigText;\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, source, 'utf8');
console.log(`Сформирован снимок ${names.length} конфигов: ${outputPath}`);
